### ISSUE TITLE
furnace not cooking with lignite coal

### ISSUE THREAD

**Issue by VaporeonScripts** [firstdarkdev/pocketmachines#3]
![Image](https://github.com/user-attachments/assets/113ad6f3-7ab5-4531-9ed2-5e13036d48be)

**Comment by NighthowlerStudios** [comment]
You are currently using a pocket **Furnace**.  The mod in question supposedly only lets this coal be used in **Blast Furnaces**

**Comment by VaporeonScripts** [comment]
well, that coal is used in furnaces aswell, lel

**Comment by NighthowlerStudios** [comment]
I don't see any proof of that from their documentation.  Please try using a pocket Blast Furnace instead, first.

**Comment by VaporeonScripts** [comment]
![Image](https://github.com/user-attachments/assets/fe226424-d23a-4cdd-a7fc-3316b74deecd)
is this enough :grin: (this is a normal furnace lmao)

**Comment by NighthowlerStudios** [comment]
The resource pack does not tell me if that's a Blast Furnace or not.

**Comment by VaporeonScripts** [comment]
![Image](https://github.com/user-attachments/assets/e46d07ef-502e-4a26-9c97-a3d3da5c0606)
![Image](https://github.com/user-attachments/assets/88623170-af66-4a9c-ba37-68b93b6779cd)
![Image](https://github.com/user-attachments/assets/bd554067-4359-471f-98a1-170b18d551a5)
![Image](https://github.com/user-attachments/assets/8c29e170-e238-41cf-ac6d-a3747ec3ffae)

**Comment by NighthowlerStudios** [comment]
Right.  Well, their documentation is out of date.  I'll have hyph take a look at this.

**Comment by VaporeonScripts** [comment]
alright!

**Comment by hypherionmc** [comment]
Is this on 1.21?

**Comment by VaporeonScripts** [comment]
yup,neoforge 1.21.1 .79

**Comment by hypherionmc** [comment]
Okay, can confirm it doesn't work in the pocket furnace, or blast furnace. So this is officially a bug

**Comment by hypherionmc** [comment]
Give this one a try. It should fix the issue: https://nightbloom.cc/project/pocketmachines/files/S3uHLJqt

**Comment by VaporeonScripts** [comment]
gonna try in a few mins

**Comment by VaporeonScripts** [comment]
![Image](https://github.com/user-attachments/assets/3cd91597-8eaa-488e-a537-d8034d8f43b6)
issue has been fixed, ty for ur patience and time
