### ISSUE TITLE
[Bug] Pocket Anvil voids inserted items upon closing UI

### ISSUE THREAD

**Issue by RainyJimbo** [firstdarkdev/pocketmachines#5]
Version: [NeoForge 1.21.3] Simple Pocket Machines - 1.0.1

Description: I noticed this when I lost one of my pickaxe when I had to close the UI to get more exp.

Steps to recreate:
1. Use pocket anvil
2. Insert items on slots
3. Close UI
4. Items left on the slots will now be voided

https://github.com/user-attachments/assets/f472f228-c631-42ae-914d-85754b680673

**Comment by hypherionmc** [comment]
Thanks for the report.

It does seem like it's only the anvil that is affected by this, also on 1.21.1.

Testing a fix for it, and will push out a release soon

**Comment by hypherionmc** [comment]
Test version, if you want to test it before I release it: https://nightbloom.cc/project/pocketmachines/files/aM78J6Sp

**Comment by hypherionmc** [comment]
Issue has been fixed in 1.0.2
